language: python
sudo: false
python: 2.7
cache: pip
install:
  - pip install -r requirements.txt --trusted-host dist.pinaxproject.com --quiet
before_script:
  - python manage.py migrate
script:
  - python manage.py test