language: python
sudo: false
python: 2.7
cache: pip
install:
  - pip install --upgrade pip setuptools --quiet
  - pip install -r requirements.txt --trusted-host dist.pinaxproject.com --quiet
  - pip install Image
script:
  - python manage.py test
