language: python
sudo: false
cache: pip
env:
  - TOXENV="py27"
  - TOXENV="pypy"
  #- TOXENV="py35"
  #- TOXENV="py_django110"
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install tox
script:
  - tox -e $TOXENV