language: python
sudo: false
python: 2.7
cache: pip
env:
  - TOXENV="py27"
  - TOXENV="pypy"
  #- TOXENV="py33"
  - TOXENV="py_django19"
  #- TOXENV="py_django110"
install:
  - pip install --upgrade setuptools
  - pip install --upgrade pip
  - pip install tox
script:
  - tox -e $TOXENV